version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:12.4
    steps:
      - checkout
      - run: echo "testing..."
      - run: npm install
      - run: npm test
workflows:
  version: 2
  test_and_build:
    jobs:
      - build:
          requires:
            - test
